### ISSUE TITLE
Yêu cầu - Lấy yêu cầu và giời thiệu Quản lý trang thiết bị cho BV Hồng Dân - Bạc Liêu

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Trien_Khai#38]

**Comment by lqbinh1987** [comment]
Nhờ a @vuongdh build lại cho Hồng Dân sử dụng Equipment dùm em, mà BV là **95005**

**Comment by vuongdh** [comment]
@lqbinh1987 em xin dữ liệu Hồng Dân dùm anh đi, điều chỉnh hơi nhiều nên test lại mới được

**Comment by nghivanbi** [comment]
này sao rồi @lqbinh1987?

**Comment by lqbinh1987** [comment]
Anh @vuongdh , tên dữ liệu nhe anh: binh_hongdan_equipment

**Comment by vuongdh** [comment]
@lqbinh1987 chỉ triển khai thôi hay có yêu cầu gì không em?

**Comment by vuongdh** [comment]
[Bản cập nhật Equip4.2023.08.09v1](https://gofile.me/78TQg/Q24gIyctK)
- Chạy script và test lại nha @lqbinh1987
