### ISSUE TITLE
Yêu cầu - Hỗ trợ bệnh viện Phụ sản thiết kế phiếu chỉ định cận lâm sàng ngoại trú

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Trien_Khai#41]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/09/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **25/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện phụ sản Cần Thơ**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Các vấn đề:
- A5 đứng
- Group nhóm trong nội dung các cận lâm sàng
- Sắp thứ tự cân lâm sàng (trong danh mục) trong group nhóm.
```

**Comment by lqbinh1987** [comment]
@hvtuan1987 tối nay liên hệ Mẫn  - Phụ Sản hỗ trợ nhé
