### ISSUE TITLE
Yêu cầu - Test và triển khai chức năng thể hiện số thứ tự phát thuốc đối với bệnh nhân thuộc đối tượng ưu tiên

### ISSUE THREAD

**Issue by ongtrieuhau** [dh-hos/To_Trien_Khai#46]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÔNG TRIỆU HẬU**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/12/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) ****
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện quận 12**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Thực hiện test và triển khai  theo cập nhật 
- [PrinterSmartOut](https://github.com/dh-hos/dhg.hospitalprintersmartout/blob/main/Deploy_Tools/CHANGELOG.md#v12312116)
- [Printer](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md#v32312111)

Thông tin dữ liệu [DuLieuCongTy/Database/bvq12_122023 ngay 8-9-2023.rar](https://gofile.me/78TQg/WK9NOTD15)

**Comment by lqbinh1987** [comment]
Coi này cái nhe @hvtuan1987.

**Comment by ongtrieuhau** [comment]
Cái này sao rồi @lqbinh1987 , @hvtuan1987 ?

**Comment by lqbinh1987** [comment]
Test qua cái @hvtuan1987

**Comment by nghivanbi** [comment]
@lqbinh1987 báo lại tình trạng xong chưa?

**Comment by lqbinh1987** [comment]
Đã xong

> @lqbinh1987 báo lại tình trạng xong chưa?
