### ISSUE TITLE
Yêu cầu - Triển khai bắt số thứ tự KIOS

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Trien_Khai#47]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/12/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **29/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK QUẬN Ô MÔN**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
[chi_tiet_yeu_cau](https://github.com/dh-hos/To_Lap_Trinh/issues/206)

```

**Comment by lqbinh1987** [comment]
Này khi nào thực hiện anh @nghivanbi ?

**Comment by nghivanbi** [comment]
Test trước Ordinal của Code, 29/12  bệnh viện có KIOS. Sau lễ triển khai.

**Comment by nghivanbi** [comment]
Test ok chưa @lqbinh1987 ?

**Comment by lqbinh1987** [comment]
@hvtuan1987

**Comment by nghivanbi** [comment]
Viết cho anh hướng dẫn triển khai hệ thống KIOS tổng thể bao gồm:
Tiếp nhận với cái module liên quan: Ordinal, Register, Monitor, Speaker.
Khám bệnh với các module liên quan: Prescription, Mointor, Speaker
Phát thuốc: Printer.

Hạn: 19/01/2024

**Comment by hvtuan1987** [comment]
Em gởi file Hướng dẫn sử dụng Kios
Tiếp nhận với cái module liên quan: Ordinal, Register, Monitor, Speaker.
[Uploading DH-09 HDSD_TK_SU DUNG KIOS BENH VIEN OMON.docx…]()
Do Ô Môn chưa có quy trình cho phát thuốc nên cái này em sẽ tìm hiểu và làm file hướng dẫn sau

**Comment by nghivanbi** [comment]
@lqbinh1987 bổ sung hồ sơ: kết hoạch và hồ sơ triển khai để hoàn thành hồ sơ thanh toán DHG.
