### ISSUE TITLE
Yêu cầu - Hỗ trợ bệnh viện Quận 12 in số thứ tự

### ISSUE THREAD

**Issue by ongtrieuhau** [dh-hos/To_Trien_Khai#48]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÔNG TRIỆU HẬU**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/12/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bệnh viện thiết kế lại số thứ tự ưu tiên nhưng in bằng tài khoản admin thì được, in bằng tài khoản thường không được (a.Điền đang báo lỗi vậy qua Zalo)

```
![image](https://github.com/dh-hos/To_Trien_Khai/assets/58720300/28848c97-0ec6-47f8-9d76-fb145ce754d8)
![image](https://github.com/dh-hos/To_Trien_Khai/assets/58720300/8be2dd9b-99d2-49ce-a0db-e377fde2e5ec)
![image](https://github.com/dh-hos/To_Trien_Khai/assets/58720300/591cf35f-cecb-457b-80c8-1f3d1f292216)

**Comment by nghivanbi** [comment]
Này xong chưa @lqbinh1987

**Comment by lqbinh1987** [comment]
Đã xong.

> Này xong chưa @lqbinh1987
