### ISSUE TITLE
Yêu cầu - Hệ thống cơ sở Medic nhờ áp lại danh mục cận lâm sàng dịch vụ.

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Trien_Khai#50]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/01/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **05/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77120; 77127; 77133; 77150`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Sai Gòn**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
- B1: đánh dấu xóa các cls cha không thanh BHYT (trừ công khám).
- B2: chuẩn hóa file excel áp test thử nhé.

```
[CLS DV 1-2024 (1).xls](https://github.com/dh-hos/To_Trien_Khai/files/13839090/CLS.DV.1-2024.1.xls)

**Comment by lqbinh1987** [comment]
Đã xong
