### ISSUE TITLE
Yêu cầu - Triển khai Phòng khám Medic 4

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Trien_Khai#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/01/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **12/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77000-001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA MEDIC SÀI GÒN 4**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
- Cài database, tạo dữ liệu ban đầu cho phòng khám
- Áp mã tạm: 77000-001
- Key: +QVRVJBvy4jLY4A8BLK2RxIm/SGIJoXaR17vkwxRnUGuBDjtgUuIWG7JLX9CrTScuUyPfvKsbBESJv0hiCaF2rpLWN9vKBWSZMmQRSu0YgOuBDjtgUuIWMYzpFzXMfPCsRXDTA0yVA/nmUn/bUALnuYq/krzZGuozSY4Y0Wj4UUdvJVRGjjXUfe9xBTvTjGOjcPE4qPRFkxSEOodxH8DVf1aofP9p4dgeVTTqbUVmaAIxqpSjYd3m68P6R+lfeM2E7I6UTs8FjvDcM/owypZVBN3Ttsvfyyg0rcl8HJExFXkVIhptwsaMtqtGXqiZrwDyYEAFMrEKdUEFFUvwwLUc9RC19POxOSmXI22N6bhkW8mGwM/3Vw0aU1uWYMcZc7esowJFPavHAGlLSqwEIQhYKDX3FB9KZlz0R51MKMxbiH7alihzS/0B1toZiQDjtdhPNZk0v1aH+s=

```

**Comment by lqbinh1987** [comment]
@nqhoa1005 thực hiện nhé!

**Comment by lqbinh1987** [comment]
Đã cấp key hoạt động lại.
