### ISSUE TITLE
Yêu cầu - Làm đồng bộ bệnh viện Vĩnh Thạnh

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Trien_Khai#54]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **0705/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92011`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK HUYỆN VĨNH THẠNH**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Liên hệ Điền (IT)

```

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/To_Trien_Khai/54)
<details> <summary>   ℹ️<code>2024-07-05 16:14:56</code> <code>@nghivanbi</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NxHKPmGkczbklG1rvfb'>-NxHKPmGkczbklG1rvfb</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1715072843371</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8982685937'>webhook-logs</a>]</code></details>

**Comment by lqbinh1987** [comment]
@hvtuan1987  , coi [hướng dẫn](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/DONG-BO-POSTGRES/Hau-huong-dan-trien-khai-postgres-replication.md) chổ này, tối nay 19h00 thực hiện cho anh Điền nhé.

**Comment by lqbinh1987** [comment]
Tuấn có việc đột xuất nên hẹn a Điền ngày mai 19h thực hiện rồi nhé anh @nghivanbi
